### ISSUE TITLE
Snapping in basebuildingplus does not work after updating expansions modes

### ISSUE THREAD

**Issue by kubkadl** [salutesh/DayZ-Expansion-Scripts#32]
Hey, i have a big problem.... snapping in basebuildingplus does not work after updating expansions modes. I use expansion territori. 
Until the update everything worked.

**Comment by ZSGaming1998** [comment]
why are you using bbp if you're using expansion jw?

**Comment by kubkadl** [comment]
because players on the my server want BBP. Btw more people same problem.

**Comment by Cedzz31** [comment]
Got the same problem too, had mixed results but placing item with expansion walls is really buggy and items stick to the walls so bbp was my other option but since the new update snapping has broken unfortunatly

**Comment by kubkadl** [comment]
> Got the same problem too, had mixed results but placing item with expansion walls is really buggy and items stick to the walls so bbp was my other option but since the new update snapping has broken unfortunatly

https://steamcommunity.com/sharedfiles/filedetails/?id=2448237424
Fix

**Comment by FXHND23** [comment]
Having issues with it on our server too, running the compatibility patch for BBP but now players can't place any building items including vanilla tents etc flat to the ground. Everything you try to place ends up on an ~30 degree angle from horizontal.

**Comment by macmac406** [comment]
Also got this issue, not snapping..

**Comment by LieutenantMaster** [comment]
Hello, due to a modding limitation preventing modders to detect what mods are loaded. The basebuildingplus snapping conflict can only be fixed with this mod at the moment : https://steamcommunity.com/sharedfiles/filedetails/?id=2448237424
All the other issues reported has been fixed in the last update.

If you still have issues with the snapping, change your load order to have this mod loading after expansion and/or after basebuildingplus
